name: ff_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiofiles=22.1.0=py311h06a4308_0
  - aiosqlite=0.18.0=py311h06a4308_0
  - altair=5.0.1=pyhd8ed1ab_1
  - ansi2html=1.8.0=py311h38be061_1
  - anyio=3.5.0=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow-cpp=11.0.0=h374c478_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py311h06a4308_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - azure-core=1.29.1=pyhd8ed1ab_0
  - azure-storage-blob=12.17.0=pyhd8ed1ab_0
  - babel=2.11.0=py311h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py311hbed6279_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py311h6a678d5_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bs4=4.12.2=py38hd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.05.30=h06a4308_0
  - catalogue=2.0.7=py311h06a4308_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311h06a4308_0
  - cloudpickle=2.2.1=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - comm=0.1.2=py311h06a4308_0
  - confection=0.0.4=py311h92b7b1e_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - cryptography=41.0.2=py311h22a60cf_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.6=py311h6a678d5_0
  - cython-blis=0.7.9=py311hf4808d0_0
  - dash=2.11.1=pyhd8ed1ab_0
  - dash-bootstrap-components=1.4.2=pyhd8ed1ab_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-daq=0.5.0=pyh9f0ad1d_1
  - dash-html-components=2.0.0=pyhd8ed1ab_1
  - dash_colorscales=0.0.4=pyh9f0ad1d_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dtale=3.3.0=pyhd8ed1ab_0
  - entrypoints=0.4=py311h06a4308_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - flask=2.1.3=pyhd8ed1ab_0
  - flask-compress=1.13=pyhd8ed1ab_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.3=pyhd8ed1ab_0
  - gensim=4.3.0=py311hba01205_1
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - htmlmin=0.1.12=pyhd3eb1b0_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - imagehash=4.3.1=py311h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipython=8.12.2=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311h06a4308_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h166bdaf_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_8
  - jupyter_client=7.4.9=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.3.0=py311h06a4308_0
  - jupyter_events=0.6.3=py311h06a4308_0
  - jupyter_server=1.23.4=py311h06a4308_0
  - jupyter_server_fileid=0.9.0=py311h06a4308_0
  - jupyter_server_ydoc=0.8.0=py311h06a4308_1
  - jupyter_ydoc=0.2.4=py311h06a4308_0
  - jupyterlab=3.6.3=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311h06a4308_0
  - jupyterlab_widgets=3.0.5=py311h06a4308_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=8.1.1=h251f7ec_2
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.52.0=h2d74bed_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - llvmlite=0.40.0=py311he621ea3_0
  - lxml=4.9.1=py311h1edc446_0
  - lz4=4.3.2=py311h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.6.2=py311h06a4308_0
  - matplotlib-base=3.6.2=py311h945d387_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - missingno=0.4.2=pyhd3eb1b0_1
  - mistune=0.8.4=py311h5eee18b_1000
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multimethod=1.9.1=py311h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.7=py311h6a678d5_0
  - nbclassic=0.5.5=py311h06a4308_0
  - nbclient=0.5.13=py311h06a4308_0
  - nbconvert=6.5.4=py311h06a4308_0
  - nbformat=5.7.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - notebook=6.5.4=py311h06a4308_1
  - notebook-shim=0.2.2=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.57.0=py311ha02d727_0
  - numexpr=2.8.4=py311h65dcdc2_1
  - numpy=1.23.5=py311h08b1b3b_1
  - numpy-base=1.23.5=py311hf175353_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=3.0.10=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.0=py311h06a4308_0
  - pandas=1.5.3=py311hba01205_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathy=0.10.1=py311h06a4308_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - phik=0.12.3=py311hdb19cb5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.2.1=py311h06a4308_0
  - platformdirs=2.5.2=py311h06a4308_0
  - plotly=5.9.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - preshed=3.0.6=py311h6a678d5_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py311hd8e8d9b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py311h5eee18b_0
  - pygments=2.15.1=py311h06a4308_1
  - pynndescent=0.5.10=py311h06a4308_0
  - pyodbc=4.0.34=py311h6a678d5_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.7=py311h6a678d5_0
  - pyqt5-sip=12.11.0=py311h6a678d5_0
  - pyrsistent=0.18.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python_abi=3.11=2_cp311
  - pytz=2022.7=py311h06a4308_0
  - pywavelets=1.4.1=py311h5eee18b_0
  - pyyaml=6.0=py311h5eee18b_1
  - pyzmq=23.2.0=py311h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.4.2=py311h06a4308_0
  - qtpy=2.2.0=py311h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py311h06a4308_1
  - retrying=1.3.3=py_2
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - scikit-learn=1.3.0=py311ha02d727_0
  - scipy=1.9.3=py311h08b1b3b_2
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311h06a4308_0
  - shap=0.41.0=py311ha02d727_1
  - shellingham=1.5.0=py311h06a4308_0
  - sip=6.6.2=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd3eb1b0_0
  - smart_open=5.2.1=py311h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py311h06a4308_1
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spacy=3.5.3=py311h4cb112f_0
  - spacy-legacy=3.0.12=py311h06a4308_0
  - spacy-loggers=1.0.4=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - squarify=0.4.3=py_0
  - srsly=2.4.6=py311h6a678d5_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py311h5eee18b_1
  - strsimpy=0.1.9=pyh9f0ad1d_0
  - sympy=1.11.1=py311h06a4308_0
  - tangled-up-in-unicode=0.2.0=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=py311h06a4308_0
  - thinc=8.1.10=py311h4cb112f_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.2=py311h5eee18b_0
  - tqdm=4.64.1=py311h06a4308_0
  - traitlets=5.7.1=py311h06a4308_0
  - typeguard=2.13.3=py311h06a4308_0
  - typer=0.4.1=py311h06a4308_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - umap-learn=0.5.3=py311h06a4308_0
  - unixodbc=2.3.11=h5eee18b_0
  - urllib3=1.26.16=py311h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - visions=0.7.5=py311h06a4308_0
  - wasabi=0.9.1=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.38.4=py311h06a4308_0
  - widgetsnbextension=4.0.5=py311h06a4308_0
  - xarray=2023.7.0=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xz=5.4.2=h5eee18b_0
  - y-py=0.5.9=py311h52d8a92_0
  - yaml=0.2.5=h7b6447c_0
  - ydata-profiling=4.1.1=py311h06a4308_0
  - ypy-websocket=0.8.2=py311h06a4308_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
prefix: /home/rj/anaconda3/envs/ff_env
